[project]
    authors = [
        { "name" = "Daniel Chalef", "email" = "daniel@getzep.com" },
        { "name" = "Paul Paliychuk", "email" = "paul@getzep.com" },
        { "name" = "Preston Rasmussen", "email" = "preston@getzep.com" },
    ]
    dependencies = [
        "diskcache>=5.6.3",
        "graph-service (>=1.0.0.7,<2.0.0.0)",
        "neo4j>=5.23.0",
        "numpy>=1.0.0",
        "openai>=1.53.0",
        "pydantic>=2.8.2",
        "python-dotenv>=1.0.1",
        "tenacity>=9.0.0",
    ]
    description = "A temporal graph building library"
    license = "Apache-2.0"
    name = "graphiti-core"
    packages = [{ include = "graphiti_core", from = "." }]
    readme = "README.md"
    requires-python = ">=3.10,<4"
    version = "0.10.3"

[project.urls]
    Homepage   = "https://help.getzep.com/graphiti/graphiti/overview"
    Repository = "https://github.com/getzep/graphiti"

[project.optional-dependencies]
    anthropic    = ["anthropic>=0.49.0"]
    google-genai = ["google-genai>=1.8.0"]
    groq         = ["groq>=0.2.0"]

[tool.poetry.group.dev.dependencies]
    anthropic             = ">=0.49.0"
    diskcache-stubs       = ">=5.6.3.6.20240818"
    google-genai          = ">=1.8.0"
    groq                  = ">=0.2.0"
    ipykernel             = ">=6.29.5"
    jupyterlab            = ">=4.2.4"
    langchain-anthropic   = ">=0.2.4"
    langchain-openai      = ">=0.2.6"
    langgraph             = ">=0.2.15"
    langsmith             = ">=0.1.108"
    mypy                  = ">=1.11.1"
    pytest                = ">=8.3.3"
    pytest-asyncio        = ">=0.24.0"
    pytest-xdist          = ">=3.6.1"
    ruff                  = ">=0.7.1"
    sentence-transformers = ">=3.2.1"
    transformers          = ">=4.45.2"
    voyageai              = ">=0.2.3"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.0"

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core"]

[tool.poetry]
    requires-poetry = ">=2.0"

[tool.pytest.ini_options]
    pythonpath = ["."]

[tool.ruff]
    line-length = 100

[tool.ruff.lint]
    ignore = ["E501"]
    select = [
        # pycodestyle
        "E",
        # Pyflakes
        "F",
        # pyupgrade
        "UP",
        # flake8-bugbear
        "B",
        # flake8-simplify
        "SIM",
        # isort
        "I",
    ]

[tool.ruff.format]
    docstring-code-format = true
    indent-style          = "space"
    quote-style           = "single"
